services:
  mysql:
    image: mysql:8.0
    container_name: fit_zone_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fitZ0n3
      MYSQL_DATABASE: fit_zone_db
    ports:
      - "3306:3306"
    volumes:
      - fit_zone_data:/var/lib/mysql

volumes:
  fit_zone_data: